# Generated by Django 5.0 on 2023-12-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('speciality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('degree', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('juft', '2'), ('toq', '1')], max_length=5)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_teacher', to='crm_app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='crm_app.team'),
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='science_teacher', to='crm_app.teacher')),
                ('teams', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='science_team', to='crm_app.team')),
            ],
        ),
    ]
