# Generated by Django 5.0 on 2023-12-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('science', models.ManyToManyField(to='crm_app.science', verbose_name='student_science')),
                ('teacher', models.ManyToManyField(to='crm_app.teacher', verbose_name='student_teacher')),
                ('team', models.ManyToManyField(to='crm_app.team', verbose_name='student_team')),
            ],
        ),
    ]
