# Generated by Django 5.0 on 2023-12-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='team',
        ),
    ]
